# Dependencies
# - markdown:         redcarpet
highlighter:      pygments

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Setup
# - title:            '[TITLE]'
# - tagline:          'A Jekyll theme'
# - description:      "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
# - url:              "http://[HOSTNAME]"
# - base# - url:          "[PATH]"
# - user# - name: "[USERNAME]"

# - author:
  # - name:           'Mark Otto'
  # - url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Michal Lichwa"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://michal.micro.blog"
markdown: "kramdown"
username: "michal"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Michal Lichwa"
name: "Michal Lichwa"
gravatar_hash: "09877b8a197619116d4448ec85b6c8ca"
avatar: "http://www.gravatar.com/avatar/09877b8a197619116d4448ec85b6c8ca?s=160"
full_name: "Michal Lichwa"
bio: ""
twitter_username: ""
github_username: ""